# Generated by Django 2.1.7 on 2019-04-01 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountnumber', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('sapid', models.IntegerField()),
                ('dateofjoining', models.DateField()),
                ('shareamount', models.IntegerField(default=0)),
                ('sharebalance', models.IntegerField(default=0)),
                ('cdamount', models.IntegerField(default=0)),
                ('dividend', models.FloatField()),
                ('cdbalance', models.IntegerField(default=0)),
                ('Totalamount', models.IntegerField()),
                ('sharesstartingnumber', models.IntegerField()),
                ('sharesendingnumber', models.IntegerField()),
                ('longloanprinciple', models.IntegerField()),
                ('longloaninterest', models.IntegerField()),
                ('longloanbalance', models.IntegerField()),
                ('longloanemi', models.IntegerField()),
                ('emerloanprinciple', models.IntegerField()),
                ('emerloaninterest', models.IntegerField()),
                ('emerloanbalance', models.IntegerField()),
                ('emerloanemi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.Login'),
        ),
    ]
