# Generated by Django 2.1.7 on 2019-04-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='Totalamount',
        ),
        migrations.AddField(
            model_name='account',
            name='isloantaken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='totalamount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='emerloanbalance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='emerloanemi',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='emerloaninterest',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='emerloanprinciple',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='longloanbalance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='longloanemi',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='longloaninterest',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='longloanprinciple',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='sharesendingnumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='sharesstartingnumber',
            field=models.IntegerField(null=True),
        ),
    ]
