# Generated by Django 2.2 on 2019-05-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='fdcapital',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
