# Generated by Django 2.2 on 2019-07-09 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='isloantaken',
            new_name='islongloantaken',
        ),
    ]
