# Generated by Django 2.2 on 2019-07-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='islongloantaken',
            field=models.BooleanField(default=False),
        ),
    ]
