# Generated by Django 2.2 on 2019-04-23 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='sharevalue',
        ),
    ]
