# Generated by Django 2.1.7 on 2019-04-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_interests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='cddividend',
        ),
        migrations.RemoveField(
            model_name='account',
            name='emerloaninterest',
        ),
        migrations.RemoveField(
            model_name='account',
            name='fdinterest',
        ),
        migrations.RemoveField(
            model_name='account',
            name='longloaninterest',
        ),
        migrations.AddField(
            model_name='interests',
            name='cddividend',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interests',
            name='emerloaninterest',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interests',
            name='fdinterest',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interests',
            name='longloaninterest',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
