# Generated by Django 2.1.7 on 2019-04-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_auto_20190401_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='dividend',
            field=models.FloatField(null=True),
        ),
    ]
