# Generated by Django 2.2 on 2019-07-16 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_auto_20190715_1009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cal',
        ),
    ]
