# Generated by Django 2.1 on 2018-12-17 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('status', '0002_auto_20181207_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedDeposits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fdCapital', models.IntegerField()),
                ('rateOfInterest', models.FloatField()),
                ('maturityDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loanAmount', models.IntegerField()),
                ('emi', models.IntegerField()),
                ('repaymentDue', models.DateField()),
                ('rateOfInterest', models.FloatField()),
                ('loanGivenTo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sharesStartingNumber', models.IntegerField()),
                ('sharesEndingNumber', models.IntegerField()),
                ('valueoftheshares', models.IntegerField()),
                ('shareholdersName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='account',
            old_name='accountbalance',
            new_name='corpus',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='salary',
            new_name='monthlyDeduction',
        ),
        migrations.AddField(
            model_name='account',
            name='dateofjoining',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
