# Generated by Django 2.1.7 on 2019-04-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_remove_account_fdmaturitydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='fdmaturitydate',
            field=models.DateField(null=True),
        ),
    ]
