# Generated by Django 2.2 on 2019-09-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_account_displaydownpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interests',
            name='year',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
    ]
