# Generated by Django 2.2 on 2019-12-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_auto_20191211_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharemonth',
            name='dividend',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
