# Generated by Django 2.1.7 on 2019-04-02 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_remove_account_cdinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cdinterest',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
