# Generated by Django 2.2 on 2019-07-29 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_auto_20190729_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='downpayment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
