# Generated by Django 2.1.7 on 2019-04-22 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_remove_account_sharevalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='sharevalue',
            field=models.IntegerField(default=0),
        ),
    ]
