# Generated by Django 2.1.7 on 2019-04-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_auto_20190401_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='emerloanemi',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
