# Generated by Django 2.2 on 2019-12-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_sharemonth_dividend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharemonth',
            name='dividend',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
