# Generated by Django 2.2 on 2019-04-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_account_sharevalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='emerloanamount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='emerloanbalance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='emerloaninterestamount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='emerloanprinciple',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='longloanamount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='longloanbalance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='longloanemi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='longloaninterestamount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='longloanprinciple',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
