# Generated by Django 2.2 on 2019-09-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_auto_20190916_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='longloanadditional',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
