# Generated by Django 2.1.7 on 2019-04-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_account_cdinterest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='emerloaninterest',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='fdinterest',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='fdmaturitydate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='longloaninterest',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
