# Generated by Django 2.2 on 2019-07-17 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0004_interests_year'),
        ('status', '0004_auto_20190717_0840'),
    ]

    operations = [
    ]
