# Generated by Django 2.1 on 2018-12-17 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0004_fixeddeposits_fdholder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixeddeposits',
            name='fdHolder',
        ),
    ]
