# Generated by Django 2.2 on 2019-07-18 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0005_merge_20190717_1014'),
        ('status', '0005_merge_20190717_1001'),
        ('status', '0005_merge_20190717_1012'),
    ]

    operations = [
    ]
