# Generated by Django 2.2 on 2019-05-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0005_auto_20190503_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='emerloanemi',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='longloanemi',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='interests',
            name='cddividend',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interests',
            name='emerloaninterest',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interests',
            name='fdinterest',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interests',
            name='longloaninterest',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interests',
            name='sharedividend',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
