# Generated by Django 2.1 on 2018-12-22 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0005_remove_fixeddeposits_fdholder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loanGivenTo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
