# Generated by Django 2.1 on 2018-12-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0006_auto_20181222_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deaprtmentname', models.CharField(max_length=20)),
            ],
        ),
    ]
