# Generated by Django 2.2 on 2019-07-20 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0006_merge_20190718_1537'),
        ('status', '0006_merge_20190719_1037'),
    ]

    operations = [
    ]
