# Generated by Django 2.2 on 2019-07-20 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0007_merge_20190720_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='sharesendingnumber',
            new_name='Noofshares',
        ),
        migrations.RemoveField(
            model_name='account',
            name='sharesstartingnumber',
        ),
    ]
