# Generated by Django 2.2 on 2019-05-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0007_auto_20190503_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='totalinvestment',
            field=models.IntegerField(default=0),
        ),
    ]
