# Generated by Django 2.2 on 2019-09-30 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0008_auto_20190928_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notidate',
            field=models.DateField(default=datetime.date(2019, 9, 30)),
        ),
    ]
