# Generated by Django 2.2 on 2019-09-29 06:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('status', '0008_auto_20190928_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='fdcapital',
        ),
        migrations.RemoveField(
            model_name='account',
            name='fdmaturitydate',
        ),
        migrations.AddField(
            model_name='account',
            name='FDCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notidate',
            field=models.DateField(default=datetime.date(2019, 9, 29)),
        ),
        migrations.CreateModel(
            name='FixedDeposits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fdcapital', models.IntegerField(default=0, null=True)),
                ('fdmaturitydate', models.DateField(null=True)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
