# Generated by Django 2.2 on 2019-05-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0008_account_totalinvestment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='totalamount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
