# Generated by Django 2.1 on 2018-12-22 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0009_auto_20181222_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department', to='status.Department'),
        ),
    ]
