# Generated by Django 2.2 on 2019-09-29 22:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0010_auto_20190929_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notidate',
            field=models.DateField(default=datetime.date(2019, 9, 30)),
        ),
    ]
