# Generated by Django 2.1 on 2018-12-22 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0011_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shares',
            name='shareholdersName',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
