# Generated by Django 2.2 on 2019-09-30 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0012_auto_20190930_0439'),
        ('status', '0009_auto_20190930_1402'),
    ]

    operations = [
    ]
