# Generated by Django 2.1 on 2018-12-24 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0013_auto_20181224_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='month',
            name='monthName',
        ),
        migrations.RemoveField(
            model_name='record',
            name='monthfield',
        ),
        migrations.AddField(
            model_name='month',
            name='monthfield',
            field=models.CharField(default='january', max_length=50),
        ),
        migrations.AddField(
            model_name='record',
            name='monthName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.Month'),
        ),
    ]
