# Generated by Django 2.2 on 2019-10-01 05:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0013_merge_20190930_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixeddeposits',
            name='fdmaturitydate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notidate',
            field=models.DateField(default=datetime.date(2019, 10, 1)),
        ),
    ]
