# Generated by Django 2.2 on 2019-10-05 03:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0014_auto_20191001_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='emerloandate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='longloandate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixeddeposits',
            name='fddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixeddeposits',
            name='fdnumber',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notidate',
            field=models.DateField(default=datetime.date(2019, 10, 5)),
        ),
        migrations.CreateModel(
            name='HistoryLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longloanamount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('longloandate', models.DateField(blank=True, null=True)),
                ('longloanperiod', models.IntegerField(blank=True, default=0, null=True)),
                ('emerloanamount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('emerloanperiod', models.IntegerField(blank=True, default=0, null=True)),
                ('emerloandate', models.DateField(blank=True, null=True)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='status.Account')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryFd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fdcapital', models.IntegerField(default=0, null=True)),
                ('fddate', models.DateField(blank=True, null=True)),
                ('fdmaturitydate', models.DateField(blank=True, null=True)),
                ('fdnumber', models.CharField(default=0, max_length=50, null=True)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='status.Account')),
            ],
        ),
    ]
