# Generated by Django 2.1.4 on 2019-02-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0016_auto_20190204_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='SAPid',
            field=models.IntegerField(),
        ),
    ]
