# Generated by Django 2.2 on 2019-10-06 22:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('status', '0016_auto_20191006_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryemerLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emerloanamount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('emerloanperiod', models.IntegerField(blank=True, default=0, null=True)),
                ('emerloandate', models.DateField(blank=True, null=True)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistorylongLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longloanamount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('longloandate', models.DateField(blank=True, null=True)),
                ('longloanperiod', models.IntegerField(blank=True, default=0, null=True)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='notification',
            name='notidate',
            field=models.DateField(default=datetime.date(2019, 10, 7)),
        ),
        migrations.DeleteModel(
            name='HistoryLoan',
        ),
    ]
