# Generated by Django 2.1.4 on 2019-02-04 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0017_auto_20190204_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='SAPid',
        ),
    ]
