# Generated by Django 2.2 on 2019-10-09 03:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0017_auto_20191007_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notidate',
            field=models.DateField(default=datetime.date(2019, 10, 9)),
        ),
    ]
