# Generated by Django 2.1.4 on 2019-02-14 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0018_remove_account_sapid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountholder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='account',
            name='corpus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loanAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shares',
            name='shareholdersName',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
