# Generated by Django 2.1.4 on 2019-02-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0019_auto_20190214_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loanAmount',
            field=models.IntegerField(),
        ),
    ]
