# Generated by Django 2.1.5 on 2019-02-15 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0019_auto_20190214_0825'),
        ('status', '0020_auto_20190214_1336'),
    ]

    operations = [
    ]
