# Generated by Django 2.1.5 on 2019-03-08 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0021_merge_20190215_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='corpus',
            field=models.IntegerField(default=0),
        ),
    ]
