# Generated by Django 2.1.5 on 2019-03-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0022_auto_20190308_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
