# Generated by Django 2.2 on 2019-10-10 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0023_auto_20191010_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixeddeposits',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='status.Account'),
        ),
        migrations.AlterField(
            model_name='historyfd',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='status.Account'),
        ),
    ]
