# Generated by Django 2.1.7 on 2019-03-19 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0024_account_sapid'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='dividend',
            field=models.FloatField(null=True),
        ),
    ]
