# Generated by Django 2.1.7 on 2019-03-19 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0025_account_dividend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='dividend',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
