# Generated by Django 2.1.7 on 2019-03-19 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0026_auto_20190319_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='corpus',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
