# Generated by Django 2.2 on 2019-10-22 04:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0026_auto_20191019_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notidate',
            field=models.DateField(default=datetime.date(2019, 10, 22)),
        ),
    ]
