# Generated by Django 2.1.7 on 2019-03-20 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0027_auto_20190319_0747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_Dividend', models.FloatField()),
            ],
        ),
    ]
