# Generated by Django 2.1.5 on 2019-03-20 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0028_shares_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shares',
            name='Name',
        ),
    ]
