# Generated by Django 2.2 on 2019-10-22 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0028_auto_20191022_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cdmonth',
            old_name='apr',
            new_name='April',
        ),
        migrations.RenameField(
            model_name='cdmonth',
            old_name='aug',
            new_name='August',
        ),
        migrations.RenameField(
            model_name='cdmonth',
            old_name='dec',
            new_name='December',
        ),
        migrations.RenameField(
            model_name='cdmonth',
            old_name='feb',
            new_name='February',
        ),
        migrations.RenameField(
            model_name='cdmonth',
            old_name='jan',
            new_name='Janurary',
        ),
        migrations.RenameField(
            model_name='cdmonth',
            old_name='jul',
            new_name='July',
        ),
        migrations.RenameField(
            model_name='cdmonth',
            old_name='jun',
            new_name='June',
        ),
        migrations.RenameField(
            model_name='cdmonth',
            old_name='mar',
            new_name='March',
        ),
        migrations.RenameField(
            model_name='cdmonth',
            old_name='may',
            new_name='May',
        ),
        migrations.RenameField(
            model_name='cdmonth',
            old_name='nov',
            new_name='November',
        ),
        migrations.RenameField(
            model_name='cdmonth',
            old_name='oct',
            new_name='October',
        ),
        migrations.RenameField(
            model_name='cdmonth',
            old_name='sep',
            new_name='September',
        ),
        migrations.RenameField(
            model_name='sharemonth',
            old_name='January',
            new_name='Janurary',
        ),
    ]
