# Generated by Django 2.1.7 on 2019-03-28 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0029_remove_shares_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
