# Generated by Django 2.1.7 on 2019-03-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0029_delete_dividend'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='AccountNumber',
            field=models.IntegerField(default=0),
        ),
    ]
