# Generated by Django 2.1.7 on 2019-03-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0030_account_accountnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.AlterField(
            model_name='account',
            name='AccountNumber',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
